/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: typeof import('./../.vitepress/vitepress/components/svg-icon.vue')['default']
    VpDemo: typeof import('./../.vitepress/vitepress/components/vp-demo.vue')['default']
    VpSourceCode: typeof import('./../.vitepress/vitepress/components/demo/vp-source-code.vue')['default']
  }
}
